version: "3.8"

volumes:
  pgdata: {}

networks:
  backend:
    driver: overlay
    attachable: true

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d:ro
    networks: [backend]
    deploy:
      replicas: 1
      restart_policy: { condition: on-failure }
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d store"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: php-api:latest
    # si construyes en el manager:
    # build: ../php-api
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: store
      DB_USER: admin
      DB_PASS: admin
    networks: [backend]
    depends_on: [db]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 3
      restart_policy: { condition: on-failure }
      update_config:
        parallelism: 1
        order: start-first
